# Generated by Django 3.2.15 on 2022-09-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preprocesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('salario', models.IntegerField(blank=True, null=True)),
                ('comprado', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
