# Generated by Django 3.2.15 on 2022-09-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_regresionlinealsimple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regresionlinealsimple',
            name='experiencia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
