# Generated by Django 3.2.15 on 2022-09-11 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_alter_regresionlinealsimple_experiencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.CharField(blank=True, max_length=255, null=True)),
                ('dificultad', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='regresionlinealsimple',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ml.projectml'),
        ),
    ]
