# Generated by Django 3.2.15 on 2022-09-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0004_auto_20220910_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegresionLinealMultiple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RD_Spend', models.FloatField(blank=True, null=True)),
                ('Administration', models.FloatField(blank=True, null=True)),
                ('Marketing_Spend', models.FloatField(blank=True, null=True)),
                ('State', models.CharField(blank=True, max_length=255, null=True)),
                ('Profit', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectml',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectml',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='regresionlinealsimple',
            name='proyecto',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='ml.projectml'),
        ),
    ]
