# Generated by Django 3.2.15 on 2022-09-13 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0006_auto_20220913_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectml',
            old_name='proyecto',
            new_name='title',
        ),
    ]
